sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev
install:
  - pip install .
  - pip install pytest pytest-cov pytest-django django_factory_boy codecov
script:
  - pytest --cov=./django_und
after_success:
  - codecov